### ISSUE TITLE
建議可以增加SSR個數判斷,等於3個SSR才進一步判斷牌色是否有海飛砂

### ISSUE THREAD

**Issue by dc1ps2** [Zhen-Bo/Cloudia#1]
版主您好, 建議版主可以增加如果這次抽到不足3顆SSR就不用判斷是否有海飛砂牌色了, 直接跳到下一輪10抽, 以增加判別速度

**Comment by Zhen-Bo** [comment]
首先我想說下，目前辨識速度瓶頸時卡在怎麼把截圖數據讀取到程式內。
穩定版會受到模擬器跟硬碟讀寫速度問題。通常截圖完把圖片拉出來要5秒。
而普通版是會受到你把截圖的bytecode讀取出來後，必須把windows的換行符號“\r\n“替換成linux系的“\n”(所以你圖片解析度越大，要換掉的字元會更多，所以速度會越慢),以建議解析度來說，替換一次字元大概需要0.5秒，如果以1080*1920來說，替換大概需要3.5秒。
而偵測三個聖物所需的時間大概在0.1～0.3秒。

而現在的方法大概是持續偵測到再抽一次按鈕->同時辨識三個聖物->沒有的話按再抽一次，有的話結束
如過你要辨識紅球數量的話，等於是說流程要變成:開始後->持續偵測跳過按鈕(一直截圖),有偵測到就按->持續偵測到有10個球->辨識紅球數->大於等於3個的話->按跳過->“再進行截圖一次”->判斷命中數量->按下再抽一次。
所以說你的建議是從“ ”起來的再進行截圖一次的步驟往前加工作量，這樣抽一次大概時間會變成30秒一輪。
除非你有更好的辨識流程可以提供，再做流程邏輯設計的時候，你要把自己當成是電腦，你的眼睛看到的影像1秒內只能更新一次靜止的圖片，然後你的大腦進行特徵辨識，之後操作你的手去做動作。
你會覺得這個流程會比較快是因為你的眼睛接受到的影像基本是60fps,而電腦接受到的影像是1fps,而且再說了，你就算沒有三紅球，也是要等到全部的球開完才能按再抽一次。
!!!!!!!!!!!!!!!!!!!!!!!重點再下面!!!!!!!!!!!!!!!!!!!!!!!
如果今天是可以出完球後就能按再抽一次的話你的流程確實會變快，可是實際上卻是要先看完全部球才能再按。

題外話，如果我把程式做成前台執行(就是腳本在跑的時候是操控裡的滑鼠，然後你不能動)的話，我可以把時間壓倒幾乎跟人手操作一樣快(沒有截圖數據傳輸緩慢的問題)，不過因為是前台，而我平時不會離開電腦前就不做了，不然用pyautogui可以快很多

>

**Comment by Zhen-Bo** [comment]
首先我想說下，目前辨識速度瓶頸時卡在怎麼把截圖數據讀取到程式內。
穩定版會受到模擬器跟硬碟讀寫速度問題。通常截圖完把圖片拉出來要5秒。
而普通版是會受到你把截圖的bytecode讀取出來後，必須把windows的換行符號“\r\n“替換成linux系的“\n”(所以你圖片解析度越大，要換掉的字元會更多，所以速度會越慢),以建議解析度來說，替換一次字元大概需要0.5秒，如果以1080*1920來說，替換大概需要3.5秒。
而偵測三個聖物所需的時間大概在0.1～0.3秒。

而現在的方法大概是持續偵測到再抽一次按鈕->同時辨識三個聖物->沒有的話按再抽一次，有的話結束
如過你要辨識紅球數量的話，等於是說流程要變成:開始後->持續偵測跳過按鈕(一直截圖),有偵測到就按->持續偵測到有10個球->辨識紅球數->大於等於3個的話->按跳過->“再進行截圖一次”->判斷命中數量->按下再抽一次。
所以說你的建議是從“ ”起來的再進行截圖一次的步驟往前加工作量，這樣抽一次大概時間會變成30秒一輪。
除非你有更好的辨識流程可以提供，再做流程邏輯設計的時候，你要把自己當成是電腦，你的眼睛看到的影像1秒內只能更新一次靜止的圖片，然後你的大腦進行特徵辨識，之後操作你的手去做動作。
你會覺得這個流程會比較快是因為你的眼睛接受到的影像基本是60fps,而電腦接受到的影像是1fps,而且再說了，你就算沒有三紅球，也是要等到全部的球開完才能按再抽一次。
!!!!!!!!!!!!!!!!!!!!!!!重點再下面!!!!!!!!!!!!!!!!!!!!!!!
如果今天是可以出完球後就能按再抽一次的話你的流程確實會變快，可是實際上卻是要先看完全部球才能再按。

題外話，如果我把程式做成前台執行(就是腳本在跑的時候是操控裡的滑鼠，然後你不能動)的話，我可以把時間壓倒幾乎跟人手操作一樣快(沒有截圖數據傳輸緩慢的問題)，不過因為是前台，而我平時不會離開電腦前就不做了，不然用pyautogui可以快很多

dc1ps2 <notifications@github.com> 於 2021年1月13日 週三 上午10:59 寫道：

**Comment by dc1ps2** [comment]
> 
> 首先我想說下，目前辨識速度瓶頸時卡在怎麼把截圖數據讀取到程式內。 穩定版會受到模擬器跟硬碟讀寫速度問題。通常截圖完把圖片拉出來要5秒。 而普通版是會受到你把截圖的bytecode讀取出來後，必須把windows的換行符號“\r\n“替換成linux系的“\n”(所以你圖片解析度越大，要換掉的字元會更多，所以速度會越慢),以建議解析度來說，替換一次字元大概需要0.5秒，如果以1080*1920來說，替換大概需要3.5秒。 而偵測三個聖物所需的時間大概在0.1～0.3秒。 而現在的方法大概是持續偵測到再抽一次按鈕->同時辨識三個聖物->沒有的話按再抽一次，有的話結束 如過你要辨識紅球數量的話，等於是說流程要變成:開始後->持續偵測跳過按鈕(一直截圖),有偵測到就按->持續偵測到有10個球->辨識紅球數->大於等於3個的話->按跳過->“再進行截圖一次”->判斷命中數量->按下再抽一次。 所以說你的建議是從“ ”起來的再進行截圖一次的步驟往前加工作量，這樣抽一次大概時間會變成30秒一輪。 除非你有更好的辨識流程可以提供，再做流程邏輯設計的時候，你要把自己當成是電腦，你的眼睛看到的影像1秒內只能更新一次靜止的圖片，然後你的大腦進行特徵辨識，之後操作你的手去做動作。 你會覺得這個流程會比較快是因為你的眼睛接受到的影像基本是60fps,而電腦接受到的影像是1fps,而且再說了，你就算沒有三紅球，也是要等到全部的球開完才能按再抽一次。 !!!!!!!!!!!!!!!!!!!!!!!重點再下面!!!!!!!!!!!!!!!!!!!!!!! 如果今天是可以出完球後就能按再抽一次的話你的流程確實會變快，可是實際上卻是要先看完全部球才能再按。 題外話，如果我把程式做成前台執行(就是腳本在跑的時候是操控裡的滑鼠，然後你不能動)的話，我可以把時間壓倒幾乎跟人手操作一樣快(沒有截圖數據傳輸緩慢的問題)，不過因為是前台，而我平時不會離開電腦前就不做了，不然用pyautogui可以快很多
> […](#)
謝謝版主特地說明實作原理, 的確那三顆紅珠出現的時間太短, 等於重刷的時候就必須一直判斷, 這樣反而更加重loading

**Comment by Zhen-Bo** [comment]
等等,忘了補充下==我不是版主
