### ISSUE TITLE
求助,Cloudia無法使用

### ISSUE THREAD

**Issue by kityeung1** [Zhen-Bo/Cloudia#2]
請問這個要怎樣解決?

測試圖
![2](https://user-images.githubusercontent.com/77531809/104809817-f8255900-582a-11eb-870e-5dc6f1d8621e.png)
問題圖
![1](https://user-images.githubusercontent.com/77531809/104809820-f9568600-582a-11eb-87b1-a8d51da29277.png)
已經試過重新開啟模擬器了, 我這個是夜神模擬器.
感謝

**Comment by Zhen-Bo** [comment]
回復:請去看清楚readme喔,如果真的骨氣硬要用夜神請去問有再用夜神的人呦,再不行我覺得你真的考慮換BS,不然你也可以直接執行最新版源碼,保證不會有這問題發生了,親

**Comment by Zhen-Bo** [comment]
翻譯:我沒再用夜神,只用BS,模擬器問題我沒法處理,如果你的環境跟我一樣但卻還不能執行的話,建議你直接下載源碼執行0.6版本源碼不會有任何這種問題

**Comment by kityeung1** [comment]
我現在嘗試用BS模擬器執行,等一下再看看有沒有問題. 謝謝你

**Comment by Zhen-Bo** [comment]
> 我現在嘗試用BS模擬器執行,等一下再看看有沒有問題. 謝謝你

如果EXE有問題請先用源碼試一次,有時候是ADB或是模擬器的問題,你用EXE黨下去執行我根本看不出是哪邊的問題,測試結果也只能說明你當下的截圖是正瘸的也有連接到設備,最穩定的版本就是0.6,不過我不太想把他打包成EXE檔,反正我沒收錢也不需要對誰負責

**Comment by kityeung1** [comment]
我下載了0.6版本,解壓縮後跟著你的步驟開了android5 版本的 bs, python也下載了,到"再抽一次"的畫面後, 按下了start.bat, 然後是這樣
![螢幕擷取畫面 (12)](https://user-images.githubusercontent.com/77531809/104811304-71c24480-5835-11eb-91de-932a9b266426.png)
模擬器已經開了ADB模式,是不是我有什麼步驟沒有做呢?

**Comment by Zhen-Bo** [comment]
等我慧觀落陰的那天知道你是怎麼操作後,我再告訴你
或是我會通靈的時候,幫你問問天神你做錯的步驟在哪
不想等地話GOOGLE會比較快

kityeung1 <notifications@github.com> 於 2021年1月16日 週六 下午8:01寫道：

**Comment by Zhen-Bo** [comment]
源碼我可以百分之百保證絕對沒問題

kityeung1 <notifications@github.com> 於 2021年1月16日 週六 下午7:15寫道：

**Comment by kityeung1** [comment]
我沒有懷疑你的源碼有問題,因為我根本不懂:( , 剛剛看到你更新exe包之後下載來用,不知道為什麼就成功了,感謝你的努力.

**Comment by Zhen-Bo** [comment]
我的意思是,我可以讓腳本跑起來,你沒辦法是因為你沒花時間去查詢如何要怎麼執行python
有時我真的不知道我該不該把東西隨手包起來,讓你們這種連簡單GOOGLE都不會去做的人使用
還是不包起來提高使用者素質,並保證不會被問智O問題

kityeung1 <notifications@github.com> 於 2021年1月16日 週六 下午8:54寫道：
