### ISSUE TITLE
0.8.1 Source Code 文字敘述異常 (小BUG)

### ISSUE THREAD

**Issue by LaiYueJi** [Zhen-Bo/Cloudia#3]
![image](https://user-images.githubusercontent.com/49654363/105577198-f7547000-5db2-11eb-98c3-b80e257d6acb.png)
問題如圖所示 模式選擇的地方顯示有問題。

**Comment by Zhen-Bo** [comment]
https://github.com/Zhen-Bo/Cloudia/releases/download/0.8/0.8.1.Cloudia.zip
請換0.8.1版
