### ISSUE TITLE
您好，遇到問題想請教

### ISSUE THREAD

**Issue by dimcosmos** [Zhen-Bo/Cloudia#5]
目前用BS最新版V4.260
ADB有打開，圖片有用BS擷取，然後用小畫家開啟擷取需要圖示
解析度為 540*960

裝置有手動新增
目前的問題是，在再抽一次的畫面，它會抽，然後就不會動了，不會點跳過，旁邊CMD視窗也沒有反應，如圖  手動點選跳過它也不會再點再抽一次，只能按enter離開

![123](https://user-images.githubusercontent.com/78785512/107330811-09414d00-6aed-11eb-9586-9bb31ad93b6b.png)

File "core\tool.py", line 209, in gatcha: [error] OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

**Comment by Zhen-Bo** [comment]
你自己製作的模板圖有問題，請照著巴哈文章的步驟做，不然請使用預設模板圖

dimcosmos <notifications@github.com> 於 2021年2月9日 週二 下午3:43 寫道：

**Comment by dimcosmos** [comment]
解決了!   
我竟然沒有測原本的能不能用= =  
不過我都按照步驟來，bs截屏，用小畫家開啟，然後匡需要的圖片，另存檔案到images裡面，搞了老半天，後來還是用按鍵精靈= =

**Comment by Zhen-Bo** [comment]
請問你製作模版圖的截圖是在模擬器解析度1080*1920的情況下截圖的嗎?文中有寫
如果你是在解析度540*960的情況下截圖然後去進行模板圖製作100%不會運作

dimcosmos <notifications@github.com> 於 2021年2月9日 週二 下午7:02寫道：

**Comment by dimcosmos** [comment]
我一開始用1080*1920  取圖，後來發現文章說要用540*960 ，因為截圖後覺的兩種解析度畫面大小品質都一樣，就混在一起了....orz   
麻煩您了 ，也祝您新的一年財源廣進，身體康泰

**Comment by Zhen-Bo** [comment]
前者是模板圖要截取的比例,後者是建議掛機的解析度,你就算用1080*1920(或任意9:16)的解析度都行並沒有規定,有規定的只有製作模板圖時一定要用1080*1920截取

dimcosmos <notifications@github.com> 於 2021年2月9日 週二 下午7:23寫道：

**Comment by dimcosmos** [comment]
了解，不過我也想不明白問題在哪，因為都按照比例擷取，比較有可能是小畫家擷取貼上那邊出錯吧，等抽到卡再來研究好了 = =  
2w抽都還沒看到命中數量  3    qq  用按鍵精靈可能會刷到放棄XD

**Comment by Zhen-Bo** [comment]
你是只有要海島船+空挺+砂蟲吧,如果是的話請用預設模板圖就好不需要再自行製作有說道現在你也沒把你做的模板圖PO出來我不會通靈也不會觀落陰,根本不知道問題出在哪
如果你沒有打算把模板圖圖片傳上來我就覺得妳沒有在使用腳本,我就直接關閉這個issue沒問題吧

dimcosmos <notifications@github.com> 於 2021年2月10日 週三 下午3:10寫道：

**Comment by dimcosmos** [comment]
![海](https://user-images.githubusercontent.com/78785512/107491096-ad96c280-6bc5-11eb-977d-e851f6323be9.png)
![沙](https://user-images.githubusercontent.com/78785512/107491101-aec7ef80-6bc5-11eb-9783-fe6b531864a3.png)
![飛](https://user-images.githubusercontent.com/78785512/107491104-af608600-6bc5-11eb-92f7-476b812cf50a.png)

我用預設模板圖可以使用，可以關閉，辛苦了

**Comment by Zhen-Bo** [comment]
你的模板圖很明顯大小就有問題正常來說要(200*200)你的只有(150*150左右),然後你可以自己關閉這個ISSUE

**Comment by dimcosmos** [comment]
了解，謝謝喔
